#아래 코드를 appspec.yml에 추가 후 업데이트 

version: 0.0

os: linux 
#배포한 파일 위치 지정/ 지정한 폴더가 존재해야함
files:
  - source: /
    destination: /home/ec2-user/codedeploy
    overwrite: true

#배포한 파일이 ec2-user권한으로 적용됌
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:

#새로운 애플리케이션 버전이 설치된 후에 실행되는 스크립트
  AfterInstall:
    - location: scripts/stop.sh    
      timeout: 60

#새로운 애플리케이션 버전이 설치된 후
  ApplicationStart:
    - location: scripts/start.sh   
      timeout: 60    
